title:       "Operating Systems 2021-2 Genap"
version:     "0039---14-Nov-2021"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-13"
author:           "Yusuf Fakhri Aldrian"
address:          "Indonesia"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://aldariaski.github.io/os212/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/aldariaski/os212/"
urlghpage:        "https://aldariaski.github.io/os212/"
keywords:         "jekyll, testing"
github:           
  - metadata

