title:       "Operating Systems 2021-2 (OS212)"
<<<<<<< HEAD
version:     "0026---20-Sep-2021"
=======
version:     "0026b---19-Sep-2021"
>>>>>>> 78ed1b5f7a3eff59987cccae62124deafa2816ac
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-13"
author:           "Cicak Bin Kadal"
address:          "Pamulang"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://cbkadal.github.io/os212/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/cbkadal/os212/"
urlghpage:        "https://cbkadal.github.io/os212/"
keywords:         "jekyll, testing"
github:           
  - metadata

